-- Create news table
create table public.news (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  summary text,
  image_url text,
  link_url text,
  published_date date default current_date,
  display_order integer generated by default as identity,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.news enable row level security;

-- Create policy for reading (public access)
create policy "Enable read access for all users" on public.news
  for select using (true);

-- Insert sample data
insert into public.news (title, summary, image_url, link_url, published_date)
values 
  ('Maia é convocada para a Seleção', 'A atacante Maia Rodrigues foi convocada para os amistosos da seleção brasileira.', 'images/convocada.png', '#', '2025-01-15'),
  ('Destaque na temporada', 'Maia lidera estatísticas de gols e assistências na temporada atual.', 'images/maia-rodrigues.png', '#', '2024-12-20'),
  ('Entrevista exclusiva', 'Confira a entrevista da jogadora falando sobre sua carreira e planos futuros.', 'images/Captura-de-Tela-2024-04-08-às-07.30-5.png', '#', '2024-11-10');
